### ISSUE TITLE
Tokens should be validated

### ISSUE THREAD

**Issue by Kordonme** [ergofriend/remix-auth-twitch#1]
First of all, thank you for creating this strategy.

I was implementing the flow myself, based on the OAuth2 strategy. So I was reading the Twitch docs and saw that [tokens should be validated](https://dev.twitch.tv/docs/authentication/validate-tokens):

> Any third-party app that calls the Twitch APIs and maintains an OAuth session **must** call the `/validate` endpoint to verify that the access token is still valid. This includes web apps, mobile apps, desktop apps, extensions, and chatbots. Your app must validate the OAuth token when it starts and on an hourly basis thereafter.

I can see that you [simply call the Twitch users endpoint](https://github.com/ergofriend/remix-auth-twitch/blob/1f765a4b5f32cba93c39052c165b12a78e1a8ac6/src/twitch.ts#L111-L117) without ever validating the token. Is this an oversight?

**Comment by ergofriend** [comment]
@Kordonme
I must have missed it, thanks for the report.
Please wait a bit as I will check this weekend.
